// var firstName = prompt('enter your first name')
// var lastName = prompt('enter your last name') 
// alert(firstName + " " + lastName)
// var phone = prompt('enter your favorite phone')
// alert(phone)
// alert(phone.length)
// var pakistani= prompt('N')
// alert(pakistani.length)
// var helloword= prompt('i')
//  alert(helloword.length)
// var string=('hyderabad')
// var change=string.replace('hyder','islam')
// alert(change)
// var doc=('472')
// var com=Number(doc)
// var num =472
// var has=num.toString()
// document.write('value :' + doc ,"<br>" + 'type : string ' + "<br>" + 'value :'+num + '<br>' + 'type : number' )
// var name='peanuts'
// var doc=name.toUpperCase()
// document.write('user input :' + name  + "<br>" +   'UPPER CASE :' + doc)
// var name=('javascript')
// var doc=name.slice(0,1)
// var string=name.slice(1)
// var com= doc.toUpperCase() + string.toLowerCase()
// document.write("User input :" + name + "<br>" + "Title case :" + com )
// var num=('35.36')
// var com=num.replace(".", "")
// document.write("Number :" + num + "<br>" + "result :" + com) 
