// var num =('3.45124')
// document.write('number :' + num + "<br>")
// document.write('round off value :' + Math.round(num) + "<br>")
// document.write('floor value :'  + Math.floor(num) + "<br>")
// document.write('ceil value :'  + Math.ceil(num) + "<br>")
var num =-2.673;
document.write('number :' + num + '<br>')
document.write('round off value :' + Math.round(num) + '<br>') 
document.write('floor value :' + Math.floor(num) + '<br>')
document.write('ceil value :' + Math.ceil(num) + '<br>')